"""
Django settings for awsInv project.

Generated by 'django-admin startproject' using Django 2.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'e0-m#f)*ya$0!b^zb16mp*b8=f##e2ge4@2e(66ip04328en2@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'awsazure',
    'azure',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'awsInv.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'awsInv.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]


AWS_SUPPORTED = [
't3.nano','t3.micro','t3.small','t3.medium','t3.large','t3.xlarge','t2.nano','t2.micro','t2.small','t2.medium','t2.large','t2.xlarge','t2.2xlarge','m5.large','m5.xlarge','m5.2xlarge','m5.4xlarge',
'm5.12xlarge','m5.24xlarge','m5.metal','m5d.large','m5d.xlarge','m5d.2xlarge','m5d.4xlarge','m5d.12xlarge','m5d.24xlarge','m5d.metal','m5a.large','m5a.large','m5a.2xlarge','m5a.4xlarge','m5a.12xlarge','m5a.24xlarge','m5ad.large','m5ad.xlarge','m5ad.2xlarge','m5ad.4xlarge','m5ad.12xlarge','m5ad.24xlarge',
'm4.large','m4.xlarge','m4.2xlarge','m4.4xlarge','m4.10xlarge','m4.16xlarge','a1.medium','a1.large','a1.xlarge','a1.2xlarge','a1.4xlarge','c5.large','c5.xlarge','c5.2xlarge','c5.4xlarge','c5.9xlarge','c5.18xlarge','c5d.large','c5d.xlarge','c5d.2xlarge','c5d.4xlarge','c5d.9xlarge','c5d.18xlarge','c5n.large','c5n.xlarge','c5n.2xlarge','c5n.4xlarge','c5n.9xlarge','c5n.18xlarge','c4.large','c4.xlarge','c4.2xlarge','c4.4xlarge','c4.8xlarge',
'r5.large','r5.xlarge','r5.2xlarge','r5.4xlarge','r5.12xlarge','r5.24xlarge','r5.metal','r5d.large','r5d.xlarge','r5d.2xlarge','r5d.4xlarge','r5d.12xlarge','r5d.24xlarge','r5d.metal','r5a.large','r5a.xlarge','r5a.2xlarge','r5a.4xlarge','r5a.12xlarge','r5a.24xlarge','r5ad.large','r5ad.xlarge','r5ad.2xlarge','r5ad.4xlarge','r5ad.4xlarge','r5ad.12xlarge','r5ad.24xlarge',
'r4.large','r4.xlarge','r4.2xlarge','r4.4xlarge','r4.8xlarge','r4.16xlarge','x1.16xlarge','x1.32xlarge','z1d.large','z1d.xlarge','z1d.2xlarge','z1d.3xlarge','z1d.6xlarge','z1d.12xlarge','z1d.metal'
]


AZURE_SUPPORTED = {
'Standard_A2','Standard_A3','Standard_A5','Standard_A4','Standard_A6','Standard_A7','Standard_D1','Standard_D2','Standard_D3','Standard_D4','Standard_D11','Standard_D12','Standard_A1_v2',
'Standard_A2m_v2','Standard_A2_v2','Standard_A4m_v2','Standard_A4_v2','Standard_A8m_v2','Standard_A8_v2','Standard_DS11','Standard_DS12','Standard_DS13',
'Standard_D11_v2','Standard_D12_v2','Standard_D13_v2','Standard_D2_v2_Promo','Standard_D3_v2_Promo','Standard_D4_v2_Promo','Standard_D11_v2_Promo','Standard_D12_v2_Promo','Standard_D13_v2_Promo',
'Standard_F1','Standard_F2','Standard_F4','Standard_F8','Standard_B1ms','Standard_B1s','Standard_B2ms','Standard_B2s','Standard_B4ms','Standard_B8ms','Standard_DS1_v2','Standard_DS2_v2','Standard_DS3_v2','Standard_DS4_v2',
'Standard_DS11_v2','Standard_DS12_v2','Standard_DS13_v2','Standard_DS11_v2_Promo','Standard_DS12_v2_Promo','Standard_DS13_v2_Promo','Standard_D2_v3','Standard_D4_v3','Standard_D8_v3',
'Standard_E2_v3','Standard_E4_v3','Standard_E8_v3','Standard_E2s_v3','Standard_E4s_v3','Standard_E8s_v3'
}

SUPPORTED_OS = ['Red Hat','Ubuntu','Debian','Windows','Amazon Linux','Cent OS']
DATA_UNAVAILABLE = "Data unavailable"